### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by danya7423** [UnitonApp/.github#1]
**Describe the bug**
Sometimes there is an infinite loading (I waited 5 minutes, the wheel is still spinning)

**To Reproduce**
1. Go to uniton.app
2. Observe the endless loading (if it does not, refresh the page)

**Expected behavior**
There is no endless loading, the wallet works as usual.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera
 - Version: 91.0.4516.16

**Additional context**
In the network tab, in the response to the request comes the error "LITE_SERVER_TIMEOUT: timeout". I can't tell exactly where, it's always in different places

**Comment by DeFiTON** [comment]
Thank you, we are aware of this issue. It has already been fixed in the [dev version](https://dev.uniton.app). We'll fix it in the standard soon.
